### ISSUE TITLE
Compatible with windows installation (pip distribution)

### ISSUE THREAD

**Issue by VikingScientist** [TheBB/lrsplines-python#31]
After installing the `lrsplines` package from pip and running
``` python
>>> import lrspline as lr
```
I'm left with the following error message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kjetilj\AppData\Local\Continuum\anaconda3\lib\site-packages\lrspline\__init__.py", line 10, in <module>
    from . import raw
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by TheBB** [comment]
Looks like a Windows thing, I can't reproduce on Linux at least. Did we ever test the Windows builds? That is, is it a recent break or not?

**Comment by VikingScientist** [comment]
Don't think we ever tested the windows build, so not a new thing. But I've gotten the lrspline library itself to compile on windows before, so it should be possible and you got the c++ code in splipy to compile on windows so the pip part should be doable.
